// Cryptocurrencies Action Types
export const FETCH_COINS_LIST_DATA = 'FETCH_COINS_LIST_DATA';
export const FETCH_COINS_LIST_DATA_SUCCESS = 'FETCH_COINS_LIST_DATA_SUCCESS';
export const FETCH_COINS_LIST_DATA_FAIL = 'FETCH_COINS_LIST_DATA_FAIL';

// Cryptocurrency Details Action Types
export const FETCH_COIN_DETAILS = 'FETCH_COIN_DETAILS';
export const FETCH_COIN_DETAILS_SUCCESS = 'FETCH_COIN_DETAILS_SUCCESS';
export const FETCH_COIN_DETAILS_FAIL = 'FETCH_COIN_DETAILS_FAIL';
