export const FETCH_CRYPTO_DATA = 'FETCH_CRYPTO_DATA';
export const FETCH_CRYPTO_DATA_SUCCESS = 'FETCH_CRYPTO_DATA_SUCCESS';
export const FETCH_CRYPTO_DATA_FAIL = 'FETCH_CRYPTO_DATA_FAIL';
export const FETCH_CRYPTO_DETAILS = 'FETCH_CRYPTO_DETAILS';
export const FETCH_CRYPTO_DETAILS_SUCCESS = 'FETCH_CRYPTO_DETAILS_SUCCESS';
export const FETCH_CRYPTO_DETAILS_FAIL = 'FETCH_CRYPTO_DETAILS_FAIL';
